### ISSUE TITLE
Cells containing hyperlinks do not scale correctly

### ISSUE THREAD

**Issue by datasynergyuk** [jovibor/ListEx#1]
The cell font size can be changed using Ctrl-Mouse Wheel. However, this doesn't work for cells that contain hyperlinks.

![HyperlinkIssue](https://user-images.githubusercontent.com/48149668/82431714-ee263d00-9a86-11ea-989c-20a5a2062c57.jpg)

**Comment by jovibor** [comment]
Fixed in c970348.

**Comment by datasynergyuk** [comment]
Thank you.
