### ISSUE TITLE
when I use SetItemText method,  Error is: Debug Assertion Failed!

### ISSUE THREAD

**Issue by LetExchange** [jovibor/ListEx#4]
1.vs2019, I uncomment the code snippet, and run the sample. the result is "Debug Assertion Failed!"
//For classical list.
/*
    ...
	m_pList->SetItemText(0, 1, L"Test item - row:0/column:1....");
    ...
*/
![图片](https://user-images.githubusercontent.com/28613064/116022344-991e7e00-a67c-11eb-9b64-ce3b4c66995b.png)

2. use other way:
	int nIndex = m_pList->GetItemCount();
	LV_ITEM lvitemAdd = { 0 };
	lvitemAdd.mask = LVIF_TEXT;
	lvitemAdd.iItem = nIndex;
	lvitemAdd.iSubItem = 0;
	lvitemAdd.pszText = _T("Test item - row:0");;
	if (m_pList->InsertItem(&lvitemAdd) != -1)
	{
		LV_ITEM lvitem = { 0 };
		lvitem.mask = LVIF_TEXT;
		lvitem.iItem = nIndex;
		lvitem.iSubItem = 1;
		lvitem.pszText = _T("Test item - row:1");
		m_pList->SetItem(&lvitem);
	}
the cell is null.

**Comment by jovibor** [comment]
Please use English here.
From the code above I can't understand what your issue is.

**Comment by jovibor** [comment]
The problem is that you can't use this method when list is in the Virtual data mode.
`ASSERT((GetStyle() & LVS_OWNERDATA)==0);`

![image](https://user-images.githubusercontent.com/5625787/116066297-3accbc00-a6cb-11eb-9221-5c7412b8e649.png)

**Comment by LetExchange** [comment]
That's ok, thanks!
