### ISSUE TITLE
Multi-select via keyboard incomplete

### ISSUE THREAD

**Issue by datasynergyuk** [jovibor/ListEx#5]
ListEx allows multiple rows to be selected by holding ctrl (or shift) and left clicking.

The Windows list control supports the same behaviour with ctrl (or shift) + up/down arrow keys.  Suggest ListEx could be improved if it also supported keyboard input for multi-selection.

**Comment by jovibor** [comment]
But it's possible now to make such selections with arrow keys. Shift + Up/Down arrows.
Or I don't understand what you mean exactly.

**Comment by datasynergyuk** [comment]
Thank you. I did some more testing and found the following:

1. In HexCtrl Bookmark manager - It works with Shift / Arrow but seems a bit flaky if try Ctrl / Arrow. In this case, nothing happens and then subsequent Shift / Arrow doesn't always work either until row is reselected with mouse. Is ListEx maintaining keyboard state?

2. In private application (Object browser view) - Shift / Arrow doesn't work. Is something special required in ListEx creation to enable keyboard support?

**Comment by jovibor** [comment]
> In private application (Object browser view) - Shift / Arrow doesn't work

This is because of filtering mechanism.

Just change this:
```cpp
void CViewList::OnListMainKeyDown(NMHDR* pNMHDR, LRESULT* pResult)
{
	const auto pKey = reinterpret_cast<NMLVKEYDOWN*>(pNMHDR);
...
```
to this:
```cpp
void CViewList::OnListMainKeyDown(NMHDR* pNMHDR, LRESULT* pResult)
{
	const auto pKey = reinterpret_cast<NMLVKEYDOWN*>(pNMHDR);
	if (pKey->wVKey == VK_UP || pKey->wVKey == VK_DOWN)
		return;
...
```
and it should work.

**Comment by datasynergyuk** [comment]
That fixed it. Many thanks.
