### ISSUE TITLE
Column width =0 delivers an asstertion failure

### ISSUE THREAD

**Issue by Hatschiiii** [jovibor/ListEx#6]
Hi,

adding a column with width 0 causes an assertion failure in the method:
void CListExHdr::OnDrawItem(CDC* pDC, int iItem, CRect rect, BOOL bIsPressed, BOOL bIsHighlighted)
when the CMemDC memDC(*pDC, rect); is created.
Inserting a test helps : 
if(rc.IsRectEmpty())
	return;

Also in the CListEx class OnPaint() method when the MemDC is created it might crash. 

Thanks
Ralf

**Comment by jovibor** [comment]
I don't see any assertions, and there actually is such a check for a very long time:
https://github.com/jovibor/ListEx/blob/ffeb4508cf203a3a4dd6df4c52d4f0739076e2b7/ListEx/src/CListExHdr.cpp#L147
Are you sure you're using the latest version and not some very old one?
